#!/bin/bash -e

NAME="cloud-init"
ORG_PATH="github.com/elotl"
REPO_PATH="${ORG_PATH}/${NAME}"
VERSION=$(git describe --dirty --tags)
GLDFLAGS="-X main.version=\"${VERSION}\""

if [ ! -h gopath/src/${REPO_PATH} ]; then
	mkdir -p gopath/src/${ORG_PATH}
	ln -s ../../../.. gopath/src/${REPO_PATH} || exit 255
fi

export GOBIN=${PWD}
# export GOPATH=${PWD}/gopath

CGO_ENABLED=0 GOOS=linux go build -ldflags '-extldflags "-static"'  -o ${GOBIN}/${NAME} ${REPO_PATH}
